// w2-seed.ts — พิมพ์ fixtures จากข้อมูล W2 mock (tests/w2-data.ts)
// รัน: npx tsx tests/w2-seed.ts > lib/fixtures.ts
// หมายเหตุ: ถ้าใช้ Supabase ให้ seed ลง DB ตรงแทน: npx tsx supabase/seed.ts --w2
import { W2_BUDGET_DEFAULTS, W2_ROUTES, W2_VENUES, W2_ZONES } from "./w2-data";

const output = `// W2 seed fixtures — generated by tests/w2-seed.ts
// 24 venues (10 work + 6 date + 4 family + 4 photo) + 16 routes (8 origins)
// ห้ามแก้มือ — รัน script ใหม่ทุกครั้งที่ข้อมูลเปลี่ยน
import type { Intent, Route, Venue, Zone } from "./types";

export const ZONES: Zone[] = ${JSON.stringify(W2_ZONES, null, 2)};

export const VENUES: Venue[] = ${JSON.stringify(W2_VENUES, null, 2)};

export const ROUTES: Route[] = ${JSON.stringify(W2_ROUTES, null, 2)};

export const BUDGET_DEFAULTS: Record<Intent, number> = ${JSON.stringify(W2_BUDGET_DEFAULTS, null, 2)};

export const LAUNCH_ZONE = "siam";
export const STALE_DAYS = 45;
`;

console.log(output);
