// Fixtures ตาม MVP Build Spec v1.0 ข้อ 2.5 — ชื่อสถานที่เป็น placeholder
// ห้ามใช้ production: แทนที่ด้วยข้อมูลจริงจาก W2 field sprint (CSV template ข้อ 2.4)
import type { Route, Venue, Zone, Intent } from "./types";

export const ZONES: Zone[] = [
  { id: "bangkapi", name_th: "Bang Kapi", is_origin: true, km_to_siam: 13 },
  { id: "ladprao", name_th: "Lat Phrao", is_origin: true, km_to_siam: 10 },
  { id: "onnut", name_th: "On Nut", is_origin: true, km_to_siam: 11 },
  { id: "pinklao", name_th: "Pinklao", is_origin: true, km_to_siam: 12 },
  { id: "chatuchak", name_th: "Chatuchak", is_origin: true, km_to_siam: 9 },
  { id: "bangna", name_th: "Bang Na", is_origin: true, km_to_siam: 18 },
  { id: "siam", name_th: "Siam", is_origin: false, km_to_siam: 0 },
];

const LAST_VALIDATED = "2026-07-12"; // fixture: อยู่ในช่วง fresh (<45 วัน)

export const VENUES: Venue[] = [
  {
    id: "V001",
    name_th: "Work Cafe Siam Square (sample)",
    zone_id: "siam",
    category: "cafe",
    intents: ["work"],
    badge: "hit",
    hit_rank: 1,
    unseen_rank: null,
    transition_rank: 4,
    attributes: { plugs: "all", wifi_mbps: 200, seat_hours: 999, noise: "medium", parking: false, food_level: "meals", indoor: true, shade: true },
    price_per_head_min: 150,
    price_per_head_max: 250,
    open_time: "09:00",
    close_time: "21:00",
    walk_min_from_hub: 6,
    video_url: null,
    source: "sprint",
    last_validated_at: LAST_VALIDATED,
    validation_count: 12,
  },
  {
    id: "V002",
    name_th: "Beans Bar Mezzanine (sample)",
    zone_id: "siam",
    category: "cafe",
    intents: ["work"],
    badge: "hit",
    hit_rank: 2,
    unseen_rank: null,
    transition_rank: 2,
    attributes: { plugs: "some", wifi_mbps: 100, seat_hours: 4, noise: "quiet", parking: false, food_level: "drinks", indoor: true, shade: true },
    price_per_head_min: 120,
    price_per_head_max: 180,
    open_time: "08:00",
    close_time: "20:00",
    walk_min_from_hub: 3,
    video_url: null,
    source: "sprint",
    last_validated_at: LAST_VALIDATED,
    validation_count: 9,
  },
  {
    id: "V003",
    name_th: "Snack Lab (sample)",
    zone_id: "siam",
    category: "cafe",
    intents: ["work"],
    badge: "hit",
    hit_rank: 3,
    unseen_rank: null,
    transition_rank: null,
    attributes: { plugs: "some", wifi_mbps: 80, seat_hours: 3, noise: "medium", parking: false, food_level: "snacks", indoor: true, shade: true },
    price_per_head_min: 100,
    price_per_head_max: 150,
    open_time: "10:00",
    close_time: "20:00",
    walk_min_from_hub: 8,
    video_url: null,
    source: "sprint",
    last_validated_at: LAST_VALIDATED,
    validation_count: 6,
  },
  {
    id: "U001",
    name_th: "Home Cafe Soi Kasem (sample)",
    zone_id: "siam",
    category: "cafe",
    intents: ["work"],
    badge: "unseen",
    hit_rank: null,
    unseen_rank: 1,
    transition_rank: null,
    attributes: { plugs: "all", wifi_mbps: 150, seat_hours: 999, noise: "quiet", parking: true, food_level: "meals", indoor: true, shade: true },
    price_per_head_min: 120,
    price_per_head_max: 200,
    open_time: "09:00",
    close_time: "19:00",
    walk_min_from_hub: 12,
    video_url: null,
    source: "tat",
    last_validated_at: LAST_VALIDATED,
    validation_count: 5,
  },
  {
    id: "U002",
    name_th: "Backyard Garden (sample)",
    zone_id: "siam",
    category: "cafe",
    intents: ["work"],
    badge: "unseen",
    hit_rank: null,
    unseen_rank: 2,
    transition_rank: null,
    attributes: { plugs: "none", wifi_mbps: null, seat_hours: 2, noise: "quiet", parking: false, food_level: "drinks", indoor: false, shade: true },
    price_per_head_min: 100,
    price_per_head_max: 160,
    open_time: "10:00",
    close_time: "19:00",
    walk_min_from_hub: 10,
    video_url: null,
    source: "tat",
    last_validated_at: LAST_VALIDATED,
    validation_count: 2, // < 3 → ห้ามโชว์ (spec 2.6)
  },
  {
    id: "V010",
    name_th: "Riverside Bistro (sample)",
    zone_id: "siam",
    category: "restaurant",
    intents: ["date"],
    badge: "hit",
    hit_rank: 1,
    unseen_rank: null,
    transition_rank: null,
    attributes: { plugs: "none", wifi_mbps: null, seat_hours: 2, noise: "quiet", parking: true, food_level: "meals", indoor: true, shade: true },
    price_per_head_min: 400,
    price_per_head_max: 600,
    open_time: "11:00",
    close_time: "22:00",
    walk_min_from_hub: 5,
    video_url: null,
    source: "sprint",
    last_validated_at: LAST_VALIDATED,
    validation_count: 7,
  },
  {
    id: "V012",
    name_th: "Campus Night Market (sample)",
    zone_id: "siam",
    category: "market",
    intents: ["family"],
    badge: "hit",
    hit_rank: 1,
    unseen_rank: null,
    transition_rank: 3,
    attributes: { plugs: "none", wifi_mbps: null, seat_hours: null, noise: "loud", parking: true, food_level: "snacks", indoor: false, shade: false },
    price_per_head_min: 100,
    price_per_head_max: 150,
    open_time: "16:00",
    close_time: "22:00",
    walk_min_from_hub: 10,
    video_url: null,
    source: "sprint",
    last_validated_at: LAST_VALIDATED,
    validation_count: 8,
  },
  {
    id: "V013",
    name_th: "Grandma's Kitchen (sample)",
    zone_id: "siam",
    category: "restaurant",
    intents: ["work", "date"],
    badge: "hit",
    hit_rank: 2,
    unseen_rank: null,
    transition_rank: 1,
    attributes: { plugs: "none", wifi_mbps: null, seat_hours: 2, noise: "medium", parking: false, food_level: "meals", indoor: true, shade: true },
    price_per_head_min: 120,
    price_per_head_max: 180,
    open_time: "11:00",
    close_time: "22:00",
    walk_min_from_hub: 5,
    video_url: null,
    source: "sprint",
    last_validated_at: LAST_VALIDATED,
    validation_count: 10,
  },
  {
    id: "U003",
    name_th: "Rooftop Gallery (sample)",
    zone_id: "siam",
    category: "activity",
    intents: ["photo"],
    badge: "unseen",
    hit_rank: null,
    unseen_rank: 1,
    transition_rank: null,
    attributes: { plugs: "none", wifi_mbps: null, seat_hours: null, noise: "quiet", parking: false, food_level: "drinks", indoor: false, shade: true },
    price_per_head_min: 0,
    price_per_head_max: 100,
    open_time: "08:00",
    close_time: "18:00",
    walk_min_from_hub: 15,
    video_url: null,
    source: "tat",
    last_validated_at: LAST_VALIDATED,
    validation_count: 4,
  },
];

export const ROUTES: Route[] = [
  {
    id: "R001",
    origin_zone: "bangkapi",
    dest_zone: "siam",
    kind: "cheapest",
    legs: [
      { route_id: "R001", seq: 1, mode: "win", detail_th: "Win bike to Bang Kapi pier", price_min: 20, price_max: 20, minutes: 10, warning_th: null },
      { route_id: "R001", seq: 2, mode: "boat", detail_th: "Saen Saep boat to Pratunam pier", price_min: 27, price_max: 27, minutes: 33, warning_th: "Last boat 19:40" },
      { route_id: "R001", seq: 3, mode: "walk", detail_th: "Walk into Siam", price_min: 0, price_max: 0, minutes: 5, warning_th: null },
    ],
  },
  {
    id: "R002",
    origin_zone: "bangkapi",
    dest_zone: "siam",
    kind: "fastest",
    legs: [
      { route_id: "R002", seq: 1, mode: "grab", detail_th: "Grab from home to Siam", price_min: 180, price_max: 210, minutes: 35, warning_th: null },
    ],
  },
  {
    id: "R003",
    origin_zone: "ladprao",
    dest_zone: "siam",
    kind: "cheapest",
    legs: [
      { route_id: "R003", seq: 1, mode: "walk", detail_th: "Walk to BTS Ha Yaek Lat Phrao", price_min: 0, price_max: 0, minutes: 5, warning_th: null },
      { route_id: "R003", seq: 2, mode: "bts", detail_th: "BTS to Siam", price_min: 44, price_max: 44, minutes: 28, warning_th: null },
    ],
  },
  {
    id: "R004",
    origin_zone: "ladprao",
    dest_zone: "siam",
    kind: "fastest",
    legs: [
      { route_id: "R004", seq: 1, mode: "grab", detail_th: "Grab from home to Siam", price_min: 150, price_max: 180, minutes: 30, warning_th: null },
    ],
  },
  {
    id: "R005",
    origin_zone: "onnut",
    dest_zone: "siam",
    kind: "cheapest",
    legs: [
      { route_id: "R005", seq: 1, mode: "walk", detail_th: "Walk to BTS On Nut", price_min: 0, price_max: 0, minutes: 5, warning_th: null },
      { route_id: "R005", seq: 2, mode: "bts", detail_th: "BTS to Siam", price_min: 37, price_max: 37, minutes: 24, warning_th: null },
    ],
  },
  {
    id: "R006",
    origin_zone: "onnut",
    dest_zone: "siam",
    kind: "fastest",
    legs: [
      { route_id: "R006", seq: 1, mode: "grab", detail_th: "Grab from home to Siam", price_min: 140, price_max: 170, minutes: 28, warning_th: null },
    ],
  },
];

// ตาราง budget default ต่อ intent (สยาม) — spec 2.6
export const BUDGET_DEFAULTS: Record<Intent, number> = {
  work: 450,
  date: 900,
  family: 1200,
  photo: 600,
};

export const LAUNCH_ZONE = "siam";
export const STALE_DAYS = 45; // Gap Fix D
